### ISSUE TITLE
I cant make the plugin work

### ISSUE THREAD

**Issue by chococlat** [liberize/Flow.Launcher.Plugin.NumberConverter#4]
[2022-10-07.txt](https://github.com/liberize/Flow.Launcher.Plugin.NumberConverter/files/9733841/2022-10-07.txt)
After installing and typing `nc` i get this error:

```
Please open new issue in: https://github.com/liberize/Flow.Launcher.Plugin.NumberConverter/issues/new
1. upload log file: [2022-10-07.txt](https://github.com/liberize/Flow.Launcher.Plugin.NumberConverter/files/9733836/2022-10-07.txt)2022-10-07.txt
2. copy below exception message

Flow Launcher version: 1.9.5
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 10/07/2022 14:15:31
Exception:
Number Converter Exception: 
Websites: https://github.com/liberize/Flow.Launcher.Plugin.NumberConverter
Author: liberize
Version: 1.0.2
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Access is denied.
 ---> System.ComponentModel.Win32Exception (5): Access is denied.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 247
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 322
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 626
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 627
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```
An important note is that this is happening also with many other extensions, so my guess is that the cause is not internal.

**Comment by deefrawley** [comment]
Hi @chococlat , has this error been resolved in subsequent releases of Flow Launcher?
